HumanCellAtlas/dcp-cli

.travis.yml, hca/full_upload.py, hca/upload_to_cloud.py, setup.py, test/test.py
Now supports the command `hca upload s3://my-remote-bucket/fastqs/bundle`.
All files within the bundle must have all required checksums precomputed. These are: 
* sha1
* sha256
* crc32c
* s3_etag
* content-type
=> Support uploading bundle from staged s3 bucket to DSS

Makefile, hca/__init__.py, hca/added_command.py, hca/constants.py, test/test.py
* This handles data formats that the cli previously didn't decode (specifically gzip). 
* Also handles the case where you call get-files on an enormous file. Streams the content instead of loading it immediately. 
* Changes the `make test` target to include install, which pip installs the package and puts hca into the namespace. I couldn't think of another way to check that the output printed bytes - open to other suggestions if you think this is a bad solution.
=> Stream print & print bytes

Makefile, README.rst
1. Updated readme to tell users to run pip install -r requirements.txt
2. Remove pip commands from the makefile.
The large amount of changes in README.rst is because of Windows NLs.
=> Remove pip from makefile steps.

test/test.py
This is to match the server API change.
=> [easy] rename query to es_query

hca/dss/composite_commands/upload.py
When we're waiting for the async upload, we should only expect 200 (found) or 404 (not-found).  Any other error code should be considered an error.
=> Fix spin loop so it detects real errors.

hca/util/__init__.py, test/test_dss_cli.py
Add a CLI test.
Fixes #82 
Connects to #77
=> Fix typevar passthrough to argparse with typing.Optional kwargs

hca/util/__init__.py, test/test_dss_api_retry.py
1. Add a retry policy class that dictates which requests are retried and how often they are retried.
2. Add a test that uses the fake 504 mechanism in data-store to test the retry policy.
Connects to https://github.com/HumanCellAtlas/data-store/issues/485
=> Retry GET requests

test/test_dss_api_retry.py
After https://github.com/HumanCellAtlas/data-store/pull/840, the probability comes in as a header, not as a cookie.
=> Send DSS_FAKE_504_PROBABILITY as a header.

.codeclimate.yml, hca/upload/__init__.py, hca/upload/api_client.py, hca/upload/cli/list_area_command.py, hca/upload/s3_agent.py, hca/upload/upload_area.py, hca/upload/upload_area_urn.py, test/upload/cli/test_list_area.py, test/upload/python_bindings/test_list_area.py
Instead of getting the file list through the Upload API, get file list directly from S3.  This means regular listings are very fast and we avoid proxied pagination.
If we are doing long listings, get detail on batches of files from the Upload API, so we don't have to give users read access to files.  Batch 100 files at a time, so the UI is fairly response (and we don't blow API gateway timeouts).
=> upload: fix list command to work for areas with many files

hca/upload/api_client.py, hca/upload/cli/__init__.py, hca/upload/cli/upload_command.py, hca/upload/upload_config.py, requirements-dev.txt, test/upload/cli/test_config.py, test/upload/cli/test_list_area.py, test/upload/python_bindings/test_list_area.py
upload: make upload_service_api_url_template configurable
Also:
- Clean up default setting.
- Actually abort when there is not current_area.
- Remove a couple of references to HCA.
=> Remove hardcoded HCA dependencies from upload CLI

Makefile, hca/dss/__init__.py
Could use some tests and also a warning in the client's streaming API autodoc, but I'm not sure how I would set up a test case, and I'd like to postpone docs until I verify that this works in the download stress tests.
=> Retry streaming read errors in bundle download

setup.py
This avoids incompatibilities with older versions of OpenSSL and errors like this:
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
=> Bump pyOpenSSL dependency on Python 2.7

test/test_dss_api.py
https://github.com/HumanCellAtlas/data-store/pull/1178/commits/6212d1e109ee1ce0b3af06b2354d1236f176fbe5 changed the validation for subscription callbacks.
=> Provide schema for URLs.

test/test_dss_api.py
Otherwise, we time out on travis runs.
=> Cap the number of results for test_search

hca/dss/__init__.py, hca/util/__init__.py
This allows us to do ranged gets rather than restart the entire download.
Verify the resulting download for extra correctness.
Test plan: Start a download, yank the ethernet cable, plug it back in, and watch the download succeed.
=> Add HTTP resume to DCP CLI download.

Makefile, hca/upload/__init__.py, hca/upload/api_client.py, hca/upload/cli/__init__.py, hca/upload/cli/creds_command.py, hca/upload/cli/select_command.py, hca/upload/cli/upload_command.py, hca/upload/credentials_manager.py, hca/upload/upload_area.py, hca/upload/upload_config.py, test/__init__.py, test/upload/__init__.py, test/upload/cli/test_config.py, test/upload/cli/test_creds.py, test/upload/cli/test_forget.py, test/upload/cli/test_list_area.py, test/upload/cli/test_list_areas.py, test/upload/cli/test_select.py, test/upload/cli/test_upload.py, test/upload/python_bindings/test_forget_area.py, test/upload/python_bindings/test_get_credentials.py, test/upload/python_bindings/test_list_area.py, test/upload/python_bindings/test_list_areas.py, test/upload/python_bindings/test_select_area.py, test/upload/python_bindings/test_upload_file.py, test/upload/test_credentials_manager.py
instead of using IAM user for each upload area
Described in document: https://docs.google.com/document/d/1JFO75A9OR1gnCT1nYHH5p-vEaf0-TdOtOme3M3b9g3A/edit#
Paired with https://github.com/HumanCellAtlas/upload-service/pull/100
=> IAM-Not: get temporary aws credentials on demand

hca/dss/__init__.py, hca/util/__init__.py, hca/util/compat.py, requirements-dev.txt, test/test_dss_api.py
Fixes #123
Adds the ability to download files from a DSS instance given a tab-separated file with references to said files. Intuitively, one would think that the TSV only needs to contain a list of file FQIDs. So why did I not go this route? Here is the train of thought that led to the current implementation:
1) From a usability perspective it is desirable that a downloaded file is assigned the same name that the file had at submission time.
2) That file name is tracked in the bundle manifest, not the file object. Given a file's FQID one would also need the FQID of a bundle that references the file. There could be more than one bundle referencing a file. The file name could be different between those bundles. To be unambiquous, the manifest has to contain two FQIDs per row, that of  of …
=> Add `download-manifest` command; file globbing for `download`

hca/util/__init__.py, test/test_dss_api_retry.py
Additionally, hang timeout config off of client instead of method
factory so user's can more easily modify the default timeouts.
See added test for how to do that.
=> Adjust default client timeouts

hca/util/__init__.py, test/test_dss_api_retry.py, test/test_dss_swagger_spec.py
Currently, the DCP CLI fetches the DSS API definition once the first time it is run after installation and never updates after that. This change implements a strategy to refetch the DSS API definition after 7 days since the last update determined by the cached API definition's (`~/.config/hca/<base-64-encoded-swagger-url>.json`) last modified date. The refetch frequency is contestable if you guys have other ideas. 
One minor improvement we are considering is to enable content encoding on the DSS API to enable serving a compressed version of the API definition in order to minimize HCA CLI start up times. Granted, with an update policy of 1 week, this fetch would occur relatively infrequently and may go unnoticed. Further, the performance tradeoff between reducing payload size and adding a …
=> Refetch DSS API definition weekly (#79)

README.rst, hca/config.py
The current steps for configuring a DSS API host for local development do not work for more complex use cases such as creating multiple `DSSClient` instances with different API hosts. These changes simply update the current docs to provide a correct method. This is due to a number of reasons which speak to the need to refactor/rethink how configuration is implemented in the CLI. A separate issue should (and will) be created to outline this work. Briefly, a couple issues are:
- `_swagger_spec` is a class variable on `SwaggerClient` forcing all instances to share the same host
- CLI configuration (includes `swagger_url` is written and loaded from cache implicitly, providing the user little visibility/control.
Connected to (#142) (#145)
=> Update docs to correct host configuration steps (#142) (#145)

hca/upload/s3_agent.py
Show enough decimal places to keep the numbers changing, even on a slow
Internet connection.
Fixes https://github.com/HumanCellAtlas/upload-service/issues/33
=> Upload: display more precision in upload progress meter

hca/util/__init__.py, hca/util/fs_helper.py, test/test_dss_swagger_spec.py, test/test_fs_helper.py
As per @ttung's suggestion (GH-139), these changes update the cached version of the DSS API definition atomically in order to avoid a race condition. This is achieved by writing the fetched file to a temp file and renamed (`os.rename`) to the desired filename, where [the latter operation is atomic](https://stackoverflow.com/questions/2333872/atomic-writing-to-file-with-python).
07/25/18 update:
These changes also handle `os.rename` [Windows specific behavior](https://docs.python.org/2/library/os.html#os.rename) by deleting the destination file if it exists before renaming. This process is attempted multiple times (5) in order to handle a potential race condition in which the destination file is recreated in between delete and rename operations. These changes also introduce …
=> Write/update DSS API definition atomically

hca/dss/upload_to_cloud.py, hca/upload/s3_agent.py, requirements.txt
Fixes https://github.com/HumanCellAtlas/dcp-cli/issues/149
Blocked by https://github.com/HumanCellAtlas/dcplib/pull/2
=> Use s3 multipart constants as defined in dcplib

setup.py
They work on Windows, unlike setuptools scripts.
=> Switch to setuptools entry_points

docs/api.rst, docs/cli.rst, docs/conf.py, docs/index.rst, docs/readme.rst, hca/cli.py, hca/dss/__init__.py, hca/upload/__init__.py, hca/util/__init__.py, hca/util/_docs.py, requirements-dev.txt, requirements.txt
- Using sphinx-argparser to generate documentation for the CLI into cli.rst
- refactored docstrings to restructed text format
- TOC now populates in sphinx documentation
- added common links to epilog in sphinx documentation
- using sphinx RSTParser to parse docstrings into argparser
- spread out documentation across api.rst, readme.rst, cli.rst, and index.rst
- the sphinx documentation **incorrectly** marks all commands generated from a swagger doc as a `classmethod`.
=> help info for parameters appears in cli for upload and download

requirements.txt
Pending fix for https://github.com/spulec/moto/issues/1793
=> Restrict Boto3 dependency version range to 1.7.x

test/integration/upload/__init__.py
=> Remove unreachable test method

README.rst, hca/util/__init__.py, test/integration/dss/test_dss_api.py, test/integration/util/test_swagger_client.py, test/unit/util/test_get_swagger_spec.py
Resolves host configuration issues when creating multiple SwaggerClient instances across multiple threads by:
- refactoring `_swagger_spec` field from a class var to an instance var
- enabling host configuration during client initialization
Specifically, host configuration is done via the `swagger_url` parameter in the client constructor. This is because the Swagger definition, which is served by `swagger_url`, provides information about the API and is the source of truth for the API host.
Fixes #142
=> Enable programmatic SwaggerClient host configuration (#142)

hca/util/__init__.py, requirements.txt, test/integration/dss/test_dss_api.py
JWT are now generated and used for authentication with the dss as outlined in https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/wikis/Security/Authentication%20and%20Authorization/Setting%20up%20DCP%20Auth
This and https://github.com/HumanCellAtlas/data-store/pull/1542 are **dependent** on each other for integration tests to **pass**. This needs to be merge this **after** https://github.com/HumanCellAtlas/data-store/pull/1542.
=> Support for OIDC JWT for Authentication

hca/dss/__init__.py
Range HTTP requests fail and return response code 416 if the requested range is not satisfiable - e.g. requesting a range starting from 0-bytes on a 0-byte file.
Fixes #132
=> fix 0-byte file download (#132)

hca/util/__init__.py
By adding the kwarg token_expiration to a SwaggerClient request you can specify how long before a generated security token expires.
=> The life time of a token can be adjusted for authentication sessions.

hca/util/__init__.py
This should be applied to the CLI immediately to correct a discrepancy between the audience used for user and service credentials.
This code was tested manually using https://github.com/HumanCellAtlas/dcp-cli/blob/d59c02e87f1fae64d37037036e6765ae7ec1e793/test/integration/dss/test_dss_api.py#L282
=> Hot fix audience

docs/_static/text_wrapping.css, docs/cli.rst
*  The swagger doc that is used to generate the cli argparser was failing to render using sphinx-argparse because of markdown in the parameter descriptions. This was fixed by telling sphinx-argparser to expect markups.
* adding css for text wrapping long parameter descriptions in read the docs.
=> Fixing read the docs error with markup language in argsparser

hca/util/__init__.py
This will fix an issue mention [here](https://github.com/HumanCellAtlas/dcp-cli/pull/184#issuecomment-438716776), when downloading large files.
=> removing redirect for retry_policy

hca/upload/api_client.py, hca/upload/upload_area.py, hca/upload/upload_submission_state.py, test/integration/upload/__init__.py, test/integration/upload/test_api_client.py
This PR accomplishes bullet # 2 `Update hca cli to call post /uuid/filename after file upload` in https://github.com/HumanCellAtlas/upload-service/issues/227. After the api change in # 1 is promoted up through all environments, this should be merged in and a new lib version cut. Then bullet # 3 can be merged in and promoted up through upload environments
=> post to upload api after successful file upload via hca cli

hca/util/__init__.py, test/integration/dss/test_dss_api.py
- This command will work for both the CLI and Python binding
- This command fetches the current swagger doc and refreshes the client.
=> Adding refresh-swagger command

hca/cli.py, hca/util/__init__.py, hca/util/exceptions.py
This will allow us to return information regarding requests and request retries when the log level is set to warning or higher.
Partial fix for https://github.com/HumanCellAtlas/dcp-cli/issues/172
=> Apply log level to requests and urllib3

hca/upload/cli/upload_command.py, hca/upload/s3_agent.py, hca/upload/upload_area.py, test/integration/upload/cli/test_upload.py, test/integration/upload/python_bindings/test_upload_file.py
This PR allows for copy into an upload area from aws s3 as defined in ticket #231 and is related to https://github.com/HumanCellAtlas/dcp-cli/pull/217/files. With the correct policies in place, this enables cross account file transfer.
=> enable file copy from s3 to upload area

docs/conf.py
Instantiate DSSClient to generate the documentation for swagger API binding
=> Fix DSS API documentation

hca/upload/api_client.py, hca/upload/s3_agent.py, hca/util/pool.py
Users have reported issues with too many threads running. This fix reduces the number of threads running as a relationship with cpu count. This PR also adds reraise=True to all retries to ensure all errors are logged appropriately.
=> reduce threads running on upload and reraise error from tenacity on upload methods

hca/util/__init__.py
=> 301 retries are logged as info

hca/util/__init__.py
Addresses #222 .
Iterate wasn't retrying on this:
```
from hca import HCAConfig
from hca.dss import DSSClient
hca_config = HCAConfig()
hca_config['DSSClient'].swagger_url = f'https://dss.dev.data.humancellatlas.org/v1/swagger.json'
dss = DSSClient(config=hca_config)
print(len(list(dss.post_search.iterate(es_query={}, replica="aws"))))
```
And so would break on a 500, even though we should retry on 500 errors.
That's because `urllib3.util.retry` doesn't retry on POST requests.  This fixes that temporarily.
The longer term solution is here: https://github.com/HumanCellAtlas/data-store/pull/1961  See comments there for follow-up steps.
We'll have to wait a month+ for that to percolate up to `prod` though, so this is a stop-gap in the meantime.
=> [Easy] Temporary fix to allow POST requests to be retried.

hca/dss/__init__.py, test/unit/test_manifest_download.py
This directory serves as a way to compartmentalize the downloaded files and enforces that different potential download schemes do not conflict.
=> Add version directory for manifest download (fixes #251)

hca/upload/cli/select_command.py, test/integration/upload/cli/test_select.py
This is for ticket https://github.com/HumanCellAtlas/upload-service/issues/326. This allows users to pass in upload area uri without a slash when selecting it via hca cli
=> allow for not providing slashes when selecting upload area

README.rst, security.txt
Links to the centralized policy at dcp, based on the conversation here: HumanCellAtlas/dcp#274 .
=> [Easy] Centralize SECURITY.md, and delete security.txt.

hca/dss/util/__init__.py, test/unit/test_manifest_download.py
This was causing tests to fail for datastore (Sorry :disappointed:)
=> Catch exception if link exists

hca/upload/s3_agent.py
If the file size is zero, there isn't anything to upload and the second part of the conditional will result in a division by zero error.
=> Don't write to terminal if the file size is 0.

hca/dss/__init__.py, test/integration/dss/test_dss_api.py, test/integration/dss/test_dss_cli.py, test/unit/test_dss_client.py
There are a couple goals here. The first is with respect to the failing
allspark tests. The issue seemed to be because the /tmp dir was in a
separate partition from the filestore and this caused linking to fail
when the dest_path option was specified. The sensible solution would be
to place the filestore root in the same directory as dest_path. But
dest_path was poorly named. So I changed it to download_dir. The other
download funcs could use something similar I ended up solving an
auxilary goal: adding a configurable download parameter all of the
download endpoints.
The download_dir option is currently undocumented because it will be
simpler to take care of during breaking API changes in #297
=> Allow download directory to be configurable

hca/dss/util/__init__.py, test/unit/test_dss_client.py
Files in the download directory should only link to the filestore. If a link already exists this change ensure that it links to the filestore and raises an error if it links somewhere else.
=> Confirm hard link location during download (fixes #298)

hca/upload/lib/client_side_checksum_handler.py
So as to not try to read an entire large file into RAM.
=> upload: use smaller reads when doing client-side checksumming

hca/util/__init__.py
This allows checkout service redirect loops and other just-in-time API
patterns to succeed over long timeframes.
With a 30 second polling loop (Retry-After delay), 1024 redirects is
is 8 hours, which may be too long for current practical situations,
but Glacier unarchivals may theoretically be in that timeframe.
=> SwaggerClient: set max redirects to a high number

requirements.txt
It is no longer in use.
- Eliminates a binary dependency with no Linux wheels available on PyPI
- The binary extension build process introduces non-reproducibility into the build
- Developers should use crc32c instead where needed
=> Remove crcmod from direct dependencies

hca/util/__init__.py
Addresses:  #291
Allows this to work:
```
from hca import HCAConfig
from hca.dss import DSSClient
hca_config = HCAConfig()
hca_config['DSSClient'].swagger_url = f'https://dss.dev.data.humancellatlas.org/v1/swagger.json'
dss = DSSClient(config=hca_config)
for i in dss.get_collections.iterate():
print(i)
```
Running this looks like:
```
(v3nv) quokka@qcore:~/dcp-cli$ python collection_enumeration_example.py
```
```
{'uuid': 'ff9f622c-6ddf-495b-8c82-9583377c7629', 'version': '2019-05-03T113550.779252Z'}
{'uuid': 'fae9cecc-f4e0-4194-9290-7165f02515db', 'version': '2019-05-03T113358.141322Z'}
{'uuid': 'efebea4b-0bc9-45b8-aee3-b600abf1453f', 'version': '2019-05-03T113356.965509Z'}
{'uuid': 'eb1b17d5-7255-4907-97a6-142e58608c47', 'version': '2019-05-03T113357.776915Z'}
```
=> [easy] Enumerate collections.

hca/util/__init__.py, requirements.txt
Fixes #337 
This is confusing and takes a while to figure out, but I think I've got it fixed.
There is a stack of libraries (requests->urllib3->httplib) handling HTTP requests.
- [urllib3.connectionpool.HTTPConnectionPool.urlopen](https://github.com/urllib3/urllib3/blob/master/src/urllib3/connectionpool.py#L449) has a (recursive) loop for handling retries for error responses (this is what urllib3.util.retry.Retry/max_retries configures).
- urllib3 also has code in this function for handling redirects; however, when used through requests, this logic is disabled.
- Instead, the logic in [requests.sessions.SessionRedirectMixin.resolve_redirects](https://github.com/kennethreitz/requests/blob/master/requests/sessions.py#L143) is used.
When I first configured this, I erroneously assumed that …
=> Fix redirect logic when Retry-After is given with a 301 redirect

hca/cli.py, hca/default_config.json, hca/query/__init__.py, hca/query/cli.py, hca/util/__init__.py, test/unit/test_dcpquery_client.py
Because the DCP Query Service uses Swagger 3.0/OpenAPI 3.0, this also begins OpenAPI 3.0 compatibility work in the Swagger Client.
Closes https://github.com/HumanCellAtlas/query-service/issues/185
=> Begin DCP Query Service CLI

hca/dss/__init__.py, test/integration/dss/test_dss_cli.py, test/unit/test_dss_client.py
Preliminary support for `hca dss download-collection`.
Features:
* Takes advantage of parallelization in `DSSClient.download_manifest`
* Supports downloading nested collections and bundles
* Properly handles collections that contain themselves. (For what it's worth, I can't find a way to create this case in the DSS, since it prevents me from creating collections that contain collections that don't yet exist.)
* Will not download collections that contain bundles/collections that are nested too deeply (depth 4 by default, configurable)
Limitations:
* Files specified in a collection independent of a bundle cannot be downloaded. This is a limitation of `DSSClient.download_manifest`.
Closes #339
=> Add support for downloading collections

hca/dss/__init__.py, hca/util/__init__.py
This passes in the raw text formatter to the subparsers, allowing docstrings to print things like newlines in the help menu.  I also added some periods in the docstring itself to better separate the text.
=> [easy] Help menu formatting.

test/integration/dss/test_dss_cli.py, test/unit/test_dss_client.py
`hca dss download-collections` relies on `hca.dss.download_manifest`, which [currently is not tested on Windows](https://github.com/HumanCellAtlas/dcp-cli/blob/7847a6a0c48d38777bda2740843cac23bfef2bd5/test/unit/test_dss_client.py#L187), causing Windows tests for #351 to fail. (I didn't catch that, sorry...)
This PR skips `download-collections` unit tests in the same way that `download_manifest` unit tests are skipped.
=> Skip download-collections tests on Windows

hca/dss/__init__.py, test/unit/test_dss_client.py
This PR fixes several things:
- Renames the internal variables to make it more clear that the `bundle.json` is the bundle manifest
- Fixes the bundle timestamp to be the bundle version
- Return the files in `bundle.json` as an array (instead of a dict like before)
=> Fix bugs in bundle.json download

hca/util/__init__.py
Should fix this (when no collections exist):
```
from hca import HCAConfig
from hca.dss import DSSClient
hca_config = HCAConfig()
hca_config["DSSClient"].swagger_url = f"https://dss.data.humancellatlas.org/v1/swagger.json"
dss = DSSClient(config=hca_config)
def find_bundles(client, replica, project_uuid):
q = {
"query": {
"bool": {
"must": [
{
"match": {
"files.project_json.provenance.document_id": project_uuid
}
}
],
"must_not": [
{
"match": {
"files.analysis_process_json.type.text": "analysis"
}
}
]
}
}
}
for hit in client.post_search.iterate(replica=replica, es_query=q, per_page=500):
yield hit
for b in find_bundles(dss, 'aws', '2cd14cf5-f8e0-4c97-91a2-9e8957f41ea8'):
print(b)
```
Bug:
```
Traceback (most recent call last):
File "./find_bundles_for_project.py", line 45, in <module>
for …
```
=> Fix get collection iteration bug.

test/integration/dss/test_dss_api.py
clean subscription after creation on login logout test.
=> [EZ] Add Subscription Cleanup 

hca/upload/cli/upload_command.py, hca/upload/lib/s3_agent.py, hca/upload/upload_area.py, test/integration/upload/__init__.py, test/integration/upload/cli/test_upload.py, test/integration/upload/test_upload_area.py
Closes #188.
This PR changes the behavior of `hca dss upload -q` to show error messages where they were previously suppressed. This fix revealed an apparent misconfiguration in test.integration.upload.cli.test_upload that caused some failing tests to be erroneously reported as passing.
=> Show errors with `hca dss upload -q`

hca/dss/__init__.py
This commit changes :meth:`download_collection` to use
:meth:`_get_full_bundle_manifest`, which addresses two bugs:
* Previously, download-collection would not download all files
in a bundle were pagination required.
* Previously, download-collection would not check for possible
filename collisions before attempting to download a bundle.
=> Fix pagination bug in download-collection

test/integration/dss/test_dss_cli.py
There is limited to no `pty` support on Windows, so test cases calling it are skipped on Windows. Turns out that even importing `pty` can cause bad. This PR changes test behavior to only import `pty` on non-NT platforms.
=> Fix broken import causing integration test failures

hca/util/__init__.py
Given an OpenAPI specification:
```
...
path:
/foo:
get:
parameters:
- in: header
name: bar
schema:
type: string
required: true
...
```
`SwaggerClient.foo(bar="abcd")`, a functions generated after parsing this specification will not apply `bar="abcd" to the header of the request. The following PR fixes this.
=> Adding header values into request when values are present in req_args

hca/util/__init__.py, test/integration/util/test_swagger_client.py, test/res/test_swagger.json
- Check for content type application/json before trying to parse.
- Storying the modified `http_path` in `_http_path` to avoid corruption of path url when making requests. This happens in the case where a valid path: `/.well-known/openid-configuration` is replace with the invalid path: `/well_known/openid_configuration` during the request.
=> Misc fixes

requirements.txt
This is required to run the HCA CLI on MacOS Catalina.
=> Unpin cryptography dependency and set min version to 2.6.1

hca/cli.py, hca/dss/__init__.py, hca/dss/cli.py, hca/query/cli.py, hca/upload/cli/upload_command.py, hca/util/__init__.py, hca/util/_docs.py, hca/util/exceptions.py, requirements-dev.txt, requirements.txt, setup.cfg
Improvements to Python package dependencies
- Add comments noting best practices for dependency management
- Format dependency version ranges
- Remove transitive (sub) dependencies
- Update dependency minimum versions to those distributed by Ubuntu 18.04 where available
- Bound version ranges in a consistent manner and leave comments where pins are necessary
Also:
-  Fix lint issues and un-silence linter on many errors
=> Improvements to package dependency lists

hca/cli.py, hca/util/__init__.py, test/integration/dss/test_dss_cli.py
Allows for auto pagination for hca commands, turns on this feature by default.
Adds support for optional `--no-paginate` to fall back to single page response. 
Closes #461
=> auto pagination

hca/cli.py, hca/upload/cli/creds_command.py, hca/upload/cli/forget_command.py, hca/upload/cli/generate_status_report_command.py, hca/upload/cli/list_area_command.py, hca/upload/cli/list_areas_command.py, hca/upload/cli/list_file_status_command.py, hca/upload/cli/select_command.py, hca/upload/cli/upload_command.py
This PR fixes a problem with the sphinx docs that causes cli sub-command descriptions to be indented and be formatted as code blocks instead of normal text. Fixes an item in #443.
=> Fix sub-command description indentation in sphinx docs

hca/upload/cli/generate_status_report_command.py, hca/upload/cli/list_file_status_command.py
This PR modifies several flags that start with `-` but are multiword flags, like `-env`, to start with a two dashes `--env`. It makes these flags consistent with other flags. It may break scripts that use a single dash. This affects the following CLI functions:
```
hca upload status
hca upload report
```
Addresses an item in #443
=> Change flags starting with - to start with --

hca/config.py
The CLI can't be installed via normal methods anymore since it's importing dependencies when fetching the version.  This should fix: https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/data-store/-/jobs/54102
=> Fix import dependencies.

setup.py
Reverts PR #476 to the original version number in setup.py, to conform to the format expected by the release `make` rules (see `common.mk` in top level of repo).
Also see https://github.com/HumanCellAtlas/dcp-cli/pull/476/files#diff-2eeaed663bd0d25b7e608891384b7298L10
=> Update version number to revert #476

hca/dss/__init__.py, hca/util/_docs.py
This will address one of the items brought up in issue #443 
The documentation has [a paragraph](https://hca.readthedocs.io/en/latest/cli.html#download-manifest) with stray commas everywhere, this fixes the problem
=> Fix documentation - remove extra periods between paragraphs

hca/dss/__init__.py
Update the docstring of `dss download` to use the correct flag to download data only or metadata only.
Closes #452
=> Fix dss download docstring to use correct flags

hca/dss/__init__.py, hca/dss/util/__init__.py, test/unit/__init__.py, test/unit/test_dss_client.py, test/unit/util/__init__.py
Fixes race in file download where the file in the filestore could be overwritten, which would leave a dangling link to the file outside the filestore and thus a duplicate file.
=> Fix duplicate download (#450)

requirements-dev.txt
The httpie library is used in the release script. On Ubuntu, the
default, snappy installed version can cause errors.
=> Add `httpie` as dev requirement (#495)

requirements.txt
User states that an error occurs when installing the `hca` tool with [conda](https://bioconda.github.io/recipes/hca/README.html?highlight=hca)
Due to conflicting docutils version pinned in `requirements.txt` and from within botocore, conda is unable to install the `hca` tool correctly.
Issue also observed when trying to perform a `pip install -r requirements.txt` within a clean virtual env.
=> pin docutils in requirements.txt

hca/dss/util/__init__.py
This addresses a permission denied error on NFS file systems that is caused by the `os.link` call. Addresses #519 
Previously we were catching a "too many links" exception, now we are also catching a "permission denied" exception and an "operation not permitted" exception. (Note that we may be able to remove the "operation not permitted" exception number from the list of exceptions that lead us to fall back to copying.)
Useful discussion of possible approaches to solving this better: https://bugs.python.org/issue37612
Useful info about NFS and Python's os module: https://web.archive.org/web/20100912144722/http://www.unixcoding.org/NFSCoding
Note: this PR does not (yet) have tests for the new error codes being caught/handled. Tests TBA.
=> Fall back to copying when os.link raises error

test/integration/dss/test_dss_api.py, test/integration/dss/test_dss_api_retry.py, test/integration/dss/test_dss_cli.py
Removes the potential for dss-tests to be run against `dss-prod` when on an operators machine. 
See: https://github.com/DataBiosphere/azul/issues/1768
=> Remove dss-prod from testing

README.rst, common.mk, setup.py
Add deprecation within README.md
Remove uploading of .whl to pypi to force building from source
Does not allow installation via `pip install hca` see warning attached
Does allow installation via `pip install hca==7.0.0`
=> Deprecate repository
