LICENSE, README.rst
Two small fixes to make the licensing consistent with the other repos.
=> license fixes

hca/added_command.py, hca/api/composite_commands/download.py, hca/api/composite_commands/upload.py
Logging.info in upload/download doesn't print as it's happening.
When I ran `make test` Oauth2Credentials gave me an error - not sure why it did here and not in master? Anyways, I fixed that here.
=> Log to stderr and fix Oauth2Credentials inputs

hca/api/composite_commands/upload.py, hca/infra.py, test/test.py
1. If the server returns 202, we poll (with a timeout & backoff).
2. Add test.
Addresses #40 
connects to #40
=> Support async upload.

hca/api/composite_commands/download.py, hca/api/composite_commands/upload.py
Stop writing to sys.stderr and use python's logging module instead.
=> Clean up logging.

hca/api/composite_commands/download.py, hca/api/composite_commands/upload.py
This eliminates the need to put it in each code path.
=> Put response.close() in the finally clause.

.travis.yml, hca/cli.py, hca/staging/cli/__init__.py, hca/staging/cli/config_store.py, hca/staging/cli/list_areas_command.py, hca/staging/cli/select_command.py, hca/staging/cli/staging_area_urn.py, hca/staging/cli/upload_command.py, requirements-dev.txt, test/staging_cli/test_list_areas.py, test/staging_cli/test_select.py, test/staging_cli/test_upload.py
```
hca staging select <urn_or_alias>
hca staging upload <file>
hca staging areas
hca staging help
```
=> Add staging commands

hca/dss/composite_commands/upload.py
Since replica is required now, let's provide it.
=> pass in the replica to head_files

hca/upload/cli/upload_command.py, test/upload/cli/test_upload.py
and make default action to report progress.
=> Upload: --quiet option for hca upload file

hca/upload/__init__.py, hca/upload/cli/upload_command.py, hca/upload/media_type.py, hca/upload/upload_area.py, requirements.txt, test/upload/cli/test_upload.py, test/upload/python_bindings/test_upload_file.py, test/upload/test_media_type.py
As per https://docs.google.com/document/d/1TqihrgXjct9aDmTJO52_gE2WlpFysB1OkG9C8exmWTw/edit#
=> `hca upload file` now generates dcp-type media type param

hca/dss/upload_to_cloud.py, test/test_dss_api.py
Connects to https://github.com/HumanCellAtlas/data-store/issues/605
=> Set S3 content-type when uploading to fake staging area.

test/test_dss_api.py
Corresponding server-side change is https://github.com/HumanCellAtlas/data-store/pull/745
=> Rename bundle_id to bundle_fqid

hca/upload/__init__.py, hca/upload/cli/upload_command.py, hca/upload/s3_agent.py, hca/upload/upload_area.py, requirements-dev.txt, test/upload/cli/test_select.py, test/upload/cli/test_upload.py
and provide a --no-transfer-acceleration option to turn it off.
=>  Upload: Turn on S3 Transfer Acceleration by default

.gitmodules, hca/dss/upload_to_cloud.py, hca/packages/checksumming_io, requirements.txt
=> Switch to use checksumming_io from dcplib

hca/util/__init__.py
Based on the new API semantics for the data store API, it could  return "Retry-After" header as part of the HTTP 301 response. The CLI would transparently handle the retry capped at 10 attempts (to be confirmed).
urllib3 already instrumented to handle Retry-After header semantics. I had to add support for the status code HTTP 301 when handling the header semantics
=> Enable retry for HTTP 301 with Retry-After header 

hca/__init__.py, hca/config.py, test/__init__.py
Also clean up hca namespace a bit.
=> Import key modules at top level of hca package

hca/cli.py, hca/dss/cli.py, test/test_dss_api.py
Also add more information in `hca --version`.
=> Fix CLI parsers

hca/util/__init__.py
In Swagger's body schemas, `enum` and `type` are mutually exclusive.
Blocks https://github.com/HumanCellAtlas/data-store/pull/1178
=> Fix handling of enum values in JSON request bodies

hca/upload/__init__.py, hca/upload/cli/creds_command.py, hca/upload/credentials_manager.py, hca/upload/s3_agent.py, hca/upload/upload_area.py, test/upload/__init__.py, test/upload/python_bindings/test_get_credentials.py, test/upload/python_bindings/test_list_area.py, test/upload/test_credentials_manager.py
Fixes https://github.com/HumanCellAtlas/upload-service/issues/114
=> Upload: refresh AWS creds using Boto3 CredentialProvider

hca/upload/cli/upload_command.py, test/integration/upload/cli/test_upload.py, test/upload/data/nonfastq1.txt, test/upload/data/subdir1/nonfastq2.txt, test/upload/data/subdir1/test2.fastq.gz, test/upload/data/subdir2/test3.fastq.gz, test/upload/data/test1.fastq.gz
Ticket https://app.zenhub.com/workspace/o/humancellatlas/upload-service/issues/36
=> allow for directory and file extension in hca upload files command

test/upload/test_upload_submission_state.py
* To improve test coverage and ensure upload_submission_state and apiclient are tested
* Mock _get
=> add testing for api_client

requirements.txt
=> Relax boto range

requirements.txt
This matches Upload's expectations of puremagic behavior.
=> Pin puremagic < 1.5

hca/util/__init__.py
=> Support get bundle iteration.

hca/dss/__init__.py, requirements.txt, test/unit/test_manifest_download.py
Adds another download command `download_manifest_v2` which downloads with the new version format.
=> Deduplicate file downloads (fixes #234)

hca/dss/__init__.py, setup.py, test/unit/test_manifest_download.py
Needs some discussion before review.
=> Parallelize download for manifest v2 (fixes #236)

.gitlab-ci.yml, requirements-dev.txt, scripts/fetch_secret.sh
GitLab CI configuration for Linux that tests
multiple versions of Python.
The code coverage results are not uploaded
to https://codecov.io/ as that is currently being done by Travis CI.
connects to https://github.com/HumanCellAtlas/dcp-cli/issues/260
=> GitLab CI configuration for Linux

hca/upload/api_client.py
Filenames with hashes were being trimmed prior
=> use urlparse to generate url safe file names

hca/util/__init__.py, hca/util/compat.py, test/integration/dss/test_dss_cli.py
Enable login for clients that do not have access to browsers.
Resolves: #258
=> Remote Login

hca/upload/lib/api_client.py
fix prod url formatting for upload api requests
=> fix prod url formatting for upload api requests

hca/dss/__init__.py, hca/util/__init__.py, hca/util/pool.py
=> Connection pool size set to DEFAULT_THREAD_COUNT

hca/dss/__init__.py, test/integration/dss/test_dss_api.py, test/integration/dss/test_dss_cli.py, test/unit/test_dss_client.py
Resolves https://github.com/HumanCellAtlas/dcp-cli/issues/239
=> Included bundle version to download bundle directory (#239)

hca/util/__init__.py, test/integration/dss/test_dss_api.py
Added tests, since pagination/iteration should have some basic tests.
=> Add paginate method.

hca/dss/__init__.py, test/unit/test_dss_client.py
Note that this PR is based of off #317 and so should be merged after.
Now all of the information for each bundle is downloaded in parallel, and then all of the files for all of the undles are downloaded in parallel. Unavoidably both of these steps happen in sequence.
=> Improve bundle parallelism (#296)

hca/util/__init__.py, test/integration/dss/test_dss_api.py
Remove application_secrets from config file during a logout.
Addresses issue if auth_uri has been updated from dss `/internal/application_secret`
=> Logout application_secret flush

hca/dss/__init__.py
Deleted lines duplicated on L287
=> `download_manifest` docstring update

test/integration/dss/test_dss_cli.py
Some improvements were made to CLI tests in #351. This PR updates some CLI tests to take advantage of those improvements.
=> Update CLI tests for brevity

hca/dss/__init__.py
This is better than what I had written previously. Thanks @amarjandu!
=> Clarity improvement to download-collection

.gitlab-ci.yml, .travis.yml
=> [easy] Remove python3.4 (EOL) testing.

hca/dss/__init__.py, test/integration/dss/test_dss_api.py, test/unit/test_dss_client.py
Refactor download components into DownloadContext. Also make wrapper for parallelization that simplifies adding tasks.
=> Refactor download (#406)

hca/util/__init__.py, test/integration/util/test_swagger_client.py, test/res/test_swagger.json, test/unit/util/__init__.py
=> supporting allOf in swaggerclient

hca/upload/upload_area_uri.py, requirements.txt, test/integration/upload/cli/test_creds.py, test/integration/upload/cli/test_forget.py, test/integration/upload/cli/test_list_area.py, test/integration/upload/cli/test_list_areas.py, test/integration/upload/cli/test_select.py, test/unit/test_dss_client.py
Closes #409 
Closes #435 
Related to #430
=> Remove six as a dependency (closes #425)

hca/util/__init__.py, test/integration/util/test_swagger_client.py, test/res/test_swagger.json
Resolving comments. See for previous history https://github.com/HumanCellAtlas/dcp-cli/pull/448
=> Misc fixes Attempt 2

hca/util/__init__.py
Implements support for https://github.com/HumanCellAtlas/data-store/pull/2332.
Fixes #456.
=> PaginatingClientMethodFactory: Use configurable paginated content keys

test/integration/dss/test_dss_api.py
Changes callback URL , from www.example.com to method name of the test
=> DSS Subscriptions: Callback Url

test/integration/dss/test_dss_cli.py
Fixes a bug where some progress bar subtests (testing functionality
in a simulated interactive session) would fail silently and
erroneously report success because child process exit code was
not checked.
Also makes some small improvements to test assertion semantics.
=> Fix some progress bar tests failing silently

hca/dss/__init__.py, hca/dss/upload_to_cloud.py, test/integration/dss/test_dss_api.py, test/integration/dss/test_dss_api_retry.py
PR before commit reordering (https://github.com/HumanCellAtlas/dcp-cli/pull/506)
=> Close file handlers after use
